name: Build Android Preview (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'eas.json'

jobs:
  build-preview-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # Use legacy peer deps to bypass React 19 / react-native-web@0.19 peer range mismatch
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: 'true'
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Verify EAS auth (token auto mode)
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          # Newer EAS CLI auto-auths via EXPO_TOKEN; explicit login not required.
          eas whoami || echo "Using EXPO_TOKEN for non-interactive auth"

      - name: Cancel existing queued preview builds (best-effort)
        if: ${{ env.EXPO_TOKEN != '' }}
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          set +e
          IDS=$(eas build:list --status new --status in-queue --platform android --json | jq -r '.[] | select(.buildProfile=="preview") | .id')
          for id in $IDS; do
            echo "Canceling existing build $id";
            eas build:cancel $id || true;
          done
          echo "Done cancel attempts"

      - name: Build (blocking preview APK)
        id: build
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          set -e
          JSON=$(eas build --platform android --profile preview --non-interactive --json)
          echo "$JSON" | jq '.'
          BUILD_ID=$(echo "$JSON" | jq -r '.id')
          STATUS=$(echo "$JSON" | jq -r '.status')
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          if [ "$STATUS" != "finished" ]; then
            echo "Build did not finish successfully (status=$STATUS)" >&2
            exit 1
          fi
          URL=$(echo "$JSON" | jq -r '.artifacts.buildUrl')
          echo "apk_url=$URL" >> $GITHUB_OUTPUT
          echo "Artifact URL: $URL"

      - name: Summary
        run: |
          echo "APK Download URL: ${{ steps.build.outputs.apk_url }}" >> $GITHUB_STEP_SUMMARY
